import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'
import Nav from '@/components/nav'
import Footer from '@/components/footer'
import {motion} from 'framer-motion';

const inter = Inter({ subsets: ['latin'] })

export default function Work() {

    const marqueeVariants = {
        animate: {
          x: [0, -1035],
          transition: {
            x: {
              repeat: Infinity,
              repeatType: "loop",
              duration: 40.5,
              ease: "linear",
            },
          },
        },
      };

  return (
    <>
      <Head>
        <title>Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
            <Nav/>
            <div className={styles.mainContainer}>
            <div className={styles.marquee}>
                    <motion.div
                        className={styles.track}
                        variants={marqueeVariants}
                        animate="animate"
                    >
                        <h1 className={styles.marqueeText}>
                            - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK
                        </h1>
                    </motion.div>
                </div>
                <div className={styles.marquee}>
                    <motion.div
                        className={styles.track}
                        variants={marqueeVariants}
                        animate="animate"
                    >
                        <h1 className={styles.marqueeText2}>
                            - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK - WORK
                        </h1>
                    </motion.div>
                </div>
                <div className={styles.container}>
                    Work
                </div>
            </div>
            <Footer/>
        </div>
      </main>
    </>
  )
}
